---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ8N14"
stages:
  Build:
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Malware Scan:
    malwareExecuteScan: true
  Acceptance:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "768b3429trial"
    cfSpace: "dev"
    cfCredentialsId: "current-subaccount-credentials"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "a949f815trial"
    cfSpace: "dev"
    cfCredentialsId: "alternate-subaccount-credentials"
    deployType: "standard"
    tmsUpload: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "node_dev"
    credentialsId: "ctm-service-key"
